Fix some "no such provider" initialisation errors in tests
Caused by: java.security.NoSuchProviderException: no such provider: BC
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.Signature.getInstance(Signature.java:355)
	at org.bouncycastle.jcajce.NamedJcaJceHelper.createSignature(NamedJcaJceHelper.java:95)

Fix org.bouncycastle.tsp.test.NewTSPTest:

org.bouncycastle.tsp.test.NewTSPTest > testGeneral FAILED
    java.lang.ExceptionInInitializerError
        at org.bouncycastle.tsp.test.NewTSPTest.testGeneral(NewTSPTest.java:64)
        Caused by:
        java.lang.RuntimeException: java.security.NoSuchProviderException: no such provider: BC
            at org.bouncycastle.tsp.test.TSPTestUtil.<clinit>(TSPTestUtil.java:86)
            ... 1 more

java.security.NoSuchAlgorithmException: MD5WithRSAEncryption Signature not available
	at java.security.Signature.getInstance(Signature.java:224)
	at org.bouncycastle.x509.X509Util.getSignatureInstance(X509Util.java:190)
	at org.bouncycastle.x509.X509Util.calculateSignature(X509Util.java:223)
	at org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:434)
	at org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:412)
	at org.bouncycastle.tsp.test.TSPTestUtil.makeCertificate(TSPTestUtil.java:196)
	at org.bouncycastle.tsp.test.TSPTestUtil.makeCACertificate(TSPTestUtil.java:155)
	at org.bouncycastle.tsp.test.NewTSPTest.testGeneral(NewTSPTest.java:65)